"""
reflection/Reflector.py
-----------------------
Abstract base class for all Reflectors.

A Reflector accepts the three artefacts that CASCADE already produces for a
flagged method and returns a structured ReflectionResult:

    • original_code      – the existing implementation
    • synthesized_code   – code generated by CASCADE from the Javadoc (C')
    • original_doc       – the original Javadoc
    • synthesized_doc    – (optional) doc re-generated from the synthesized code

Its job is to turn those artefacts into:
    1. A typed inconsistency label (e.g. ReturnValueMismatch, BranchMismatch …)
    2. A human-readable natural-language explanation
    3. A precision_confidence score in [0, 1]

New reflectors need only inherit this class, implement `reflect()`, be placed
in this package, and be referenced by name in the cascade config file.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Optional


# ---------------------------------------------------------------------------
# Shared vocabulary of structural inconsistency types.
# Kept here so every reflector uses the same labels in its output.
# ---------------------------------------------------------------------------
class InconsistencyType:
    RETURN_VALUE_MISMATCH      = "ReturnValueMismatch"
    BRANCH_MISMATCH            = "BranchMismatch"
    EXCEPTION_CONTRACT         = "ExceptionContractViolation"
    ITERATION_MISMATCH         = "IterationMismatch"
    SIDE_EFFECT_CONTRADICTION  = "SideEffectContradiction"
    CASE_SENSITIVITY           = "CaseSensitivityMismatch"
    NULL_HANDLING              = "NullHandlingMismatch"
    UNDERDOCUMENTED            = "UnderdocumentedBehavior"
    UNKNOWN                    = "Unknown"


@dataclass
class ReflectionResult:
    """
    Structured output produced by any Reflector.

    Fields
    ------
    inconsistency_type : str
        One of the InconsistencyType constants (or a custom string for
        domain-specific reflectors).
    explanation : str
        A natural-language sentence that concisely describes *what* is
        inconsistent and *why*, written to be shown to a developer.
    precision_confidence : float
        A score in [0.0, 1.0].  High values mean the reflector is highly
        confident this is a true positive.  Can be used downstream to rank
        or filter alerts before presenting them to users.
    doc_delta_summary : Optional[str]
        A short description of how the synthesized doc differs from the
        original doc.  Set by reflectors that also generate a synthesized doc.
    code_diff_lines : list[str]
        Unified-diff lines of original vs synthesized code (for logging /
        downstream analysis).  Empty list if not computed.
    raw_metadata : dict
        Any extra data a specific reflector wants to preserve (token counts,
        individual diff hunks, etc.).
    """
    inconsistency_type: str = InconsistencyType.UNKNOWN
    explanation: str = ""
    precision_confidence: float = 0.5
    doc_delta_summary: Optional[str] = None
    code_diff_lines: list = field(default_factory=list)
    raw_metadata: dict = field(default_factory=dict)


class Reflector(ABC):
    """
    Abstract base class.  Subclasses must implement `reflect()`.

    Parameters passed via CASCADE's config `kwargs` are forwarded to
    `__init__` by the PipelineFactory, exactly like Generator subclasses.
    """

    def __init__(self, **kwargs):
        # Subclasses may accept additional kwargs (e.g. model name, thresholds)
        self._kwargs = kwargs

    # ------------------------------------------------------------------
    # Public contract
    # ------------------------------------------------------------------

    @abstractmethod
    def reflect(
        self,
        original_code: str,
        synthesized_code: str,
        original_doc: str,
        synthesized_doc: Optional[str] = None,
        p2f_count: int = 0,
        f2p_count: int = 0,
        **extra,
    ) -> ReflectionResult:
        """
        Analyse the triple (original_code, synthesized_code, original_doc)
        and optionally the synthesized_doc, then return a ReflectionResult.

        Parameters
        ----------
        original_code : str
            The raw source of the method as it exists in the repository.
        synthesized_code : str
            The implementation CASCADE generated from original_doc.
        original_doc : str
            The Javadoc / docstring as it exists in the repository.
        synthesized_doc : str, optional
            Doc regenerated from synthesized_code (only available when a
            DocGenerator step was run before this Reflector).
        p2f_count : int
            Number of tests that passed on the original but failed on the
            synthesized implementation (already in analyzed.json).
        f2p_count : int
            Number of tests that failed on the original but passed on the
            synthesized implementation (already in analyzed.json).
        **extra
            Future-proofing slot for additional artefacts.

        Returns
        -------
        ReflectionResult
        """

    # ------------------------------------------------------------------
    # Helpers available to all subclasses
    # ------------------------------------------------------------------

    @staticmethod
    def unified_diff(original: str, synthesized: str, fromfile: str = "original", tofile: str = "synthesized") -> list:
        """Return unified-diff lines between two code strings."""
        import difflib
        return list(
            difflib.unified_diff(
                original.splitlines(keepends=True),
                synthesized.splitlines(keepends=True),
                fromfile=fromfile,
                tofile=tofile,
            )
        )

    @staticmethod
    def token_overlap_ratio(text_a: str, text_b: str) -> float:
        """
        Jaccard similarity on whitespace-split tokens.
        Cheap proxy for semantic similarity between two short strings.
        """
        if not text_a or not text_b:
            return 0.0
        tokens_a = set(text_a.lower().split())
        tokens_b = set(text_b.lower().split())
        union = tokens_a | tokens_b
        if not union:
            return 1.0
        return len(tokens_a & tokens_b) / len(union)